
## Machine Learning (Supervised Learning)

Supervised learning algorithms are trained using labeled examples, such as an input where the desired output is known.
The learning algorithm receives a set of inputs along with corresponding correct outputs, and the algorithm learns by comparing its actual output with correct outputs to find errors, then modifies the model accordingly.

Through methods like classification, regression, prediction and gradient boosting, supervised learning uses patterns to predict the values of the label on additional unlabled (test data) data. 
Supervised learning is commonly used in applications where historical data predicts likley future events. 

### Example: 
Supervised learning can anticipate when credit card transactions are likely to be fraudulent of which insurance customer is likely to file a claim. It can also attempt to perdict the price of a house based on different features for houses for which we have historical price data. 

## Machine Learning (Unsupervised Learning)

Unsupervised learning is used against data that has no historical labels. The system is not told the "right answer". The algorithm must figure out what is being shown. The goal is to explore the data and find some structire within. 

### Example: 

Unsupervised learning can find the main attributes that separate customer segments from each other. Popular techniques include self-organizing maps, nearest neighbor mapping, k-means clustering and signular value decomposition. Additiionally, unsupervised learning algorithms are used to segment text topics, recommend items and identify data outliers. 

## Machine Learning (Reinforcement Learning - Neural Nets)

Reinforcement learning is often used for robotics, gaming and navigation. With reinforcement learning, the algorithm discovers through trial and error which actions yield the greatest rewards. 

This type of learning has three primary components: the agent (the learner or decision maker), the environment (everything the agent interactrs with) and actions (what the agent can do). 

The pbjective is for the agent to choose actions that maximize the expected reward over a given amount of time. The agent will reach the goal much faster by following a good policy. Goal is to find the best policy. 
